[2018-02-27 16:54:56 +0300] [5366] [INFO] Starting gunicorn 19.7.1
[2018-02-27 16:54:56 +0300] [5366] [INFO] Listening at: http://0.0.0.0:8000 (5366)
[2018-02-27 16:54:56 +0300] [5366] [INFO] Using worker: sync
[2018-02-27 16:54:56 +0300] [5369] [INFO] Booting worker with pid: 5369
[2018-02-27 16:54:56 +0300] [5369] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named 'ask'
[2018-02-27 16:54:56 +0300] [5369] [INFO] Worker exiting (pid: 5369)
[2018-02-27 16:54:56 +0300] [5366] [INFO] Shutting down: Master
[2018-02-27 16:54:56 +0300] [5366] [INFO] Reason: Worker failed to boot.
[2018-02-27 17:13:25 +0300] [6821] [INFO] Starting gunicorn 19.7.1
[2018-02-27 17:13:25 +0300] [6821] [INFO] Listening at: http://0.0.0.0:8000 (6821)
[2018-02-27 17:13:25 +0300] [6821] [INFO] Using worker: sync
[2018-02-27 17:13:25 +0300] [6824] [INFO] Booting worker with pid: 6824
[2018-02-27 17:13:25 +0300] [6824] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ImportError: No module named 'ask'
[2018-02-27 17:13:25 +0300] [6824] [INFO] Worker exiting (pid: 6824)
[2018-02-27 17:13:25 +0300] [6821] [INFO] Shutting down: Master
[2018-02-27 17:13:25 +0300] [6821] [INFO] Reason: Worker failed to boot.
